package com.alibaba.sdk.android.tbrest.rest;

/* renamed from: com.alibaba.sdk.android.tbrest.rest.a */
/* compiled from: RestFieldsScheme */
public enum C0883a {
    IMEI,
    IMSI,
    BRAND,
    DEVICE_MODEL,
    RESOLUTION,
    CARRIER,
    ACCESS,
    ACCESS_SUBTYPE,
    CHANNEL,
    f1357j,
    APPVERSION,
    LL_USERNICK,
    USERNICK,
    LL_USERID,
    USERID,
    LANGUAGE,
    OS,
    OSVERSION,
    SDKVERSION,
    START_SESSION_TIMESTAMP,
    UTDID,
    SDKTYPE,
    RESERVE2,
    RESERVE3,
    RESERVE4,
    RESERVE5,
    RESERVES,
    RECORD_TIMESTAMP,
    PAGE,
    EVENTID,
    ARG1,
    ARG2,
    ARG3,
    ARGS
}
